package delphix

type TimeflowRepairParameters interface{}
type JSUsageData interface{}
type OracleCustomEnvVarFile interface{}
type AlertAction interface{}
type SourceOperation interface{}
type PathConstraint interface{}
type ProvisionParameters interface{}
type SshVerifyBase interface{}
type OracleSource interface{}
type AttachData interface{}
type TimeflowPoint interface{}
type AppDataLinkedSource interface{}
type CallResult interface{}
type Policy interface{}
type NetworkTest interface{}
type Operation interface{}
type MySQLSyncParameters interface{}
type OracleBaseSourceRuntime interface{}
type Host interface{}
type MySQLSource interface{}
type ToolkitLinkedSource interface{}
type MSSqlBaseClusterInstance interface{}
type NetworkThroughputTestBase interface{}
type AlertFilter interface{}
type BaseSystemCapacityData interface{}
type ASESyncParameters interface{}
type Notification interface{}
type JSDataParent interface{}
type AppDataSourceConfig interface{}
type OracleBaseAttachData interface{}
type AppDataBaseTimeflow interface{}
type MSSqlBaseClusterListener interface{}
type ReadonlyNamedUserObject interface{}
type OracleTimeflowLog interface{}
type AppDataSource interface{}
type PublicKeyCredential interface{}
type TimeflowSnapshot interface{}
type AppDataManagedSource interface{}
type JSDataContainerCreateParameters interface{}
type SourceRepository interface{}
type SourceEnvironment interface{}
type SourceConnectionInfo interface{}
type AggregateCapacityData interface{}
type OracleDatafileTempfileSpecification interface{}
type NamedUserObject interface{}
type Container interface{}
type BooleanConstraint interface{}
type IntegerConstraint interface{}
type OracleDBConfig interface{}
type MSSqlRepository interface{}
type BasePlatformParameters interface{}
type EnumConstraint interface{}
type SourceEnvironmentCreateParameters interface{}
type Datapoint interface{}
type MSSqlBaseClusterRepository interface{}
type NetworkTestParameters interface{}
type Source interface{}
type JSDataLayoutCreateParameters interface{}
type SourceConfig interface{}
type PgSQLSource interface{}
type BaseSupportBundleParameters interface{}
type OracleBaseDBConfig interface{}
type AxisConstraint interface{}
type JSOperationEndpointParameters interface{}
type AlertActionEmail interface{}
type FilesystemLayout interface{}
type CreateTransformationParameters interface{}
type MSSqlDBConfig interface{}
type ReplicationObjectSpecification interface{}
type OracleSourceConnectionInfo interface{}
type AppDataLinkData interface{}
type CompatibleRepositoriesParameters interface{}
type OracleCustomEnvVarPair interface{}
type JSTimelinePointTimeParameters interface{}
type MSSqlSyncParameters interface{}
type MySQLReplicationCoordinates interface{}
type LogFetchSSH interface{}
type JSTimelinePointParameters interface{}
type MSSqlSource interface{}
type UserObject interface{}
type SchedulePolicy interface{}
type OracleBaseProvisionParameters interface{}
type TimeflowPointParameters interface{}
type Credential interface{}
type DBContainerRuntime interface{}
type MySQLExistingBackupSyncParameters interface{}
type EmptyDatasetCreationParameters interface{}
type HostCreateParameters interface{}
type NetworkThroughputTestBaseParameters interface{}
type OracleFileSpecification interface{}
type JSDataLayout interface{}
type OracleCustomEnvVar interface{}
type StringConstraint interface{}
type DbExportParameters interface{}
type BaseConsumerCapacityData interface{}
type SourceRuntime interface{}
type VirtualDatasetCreationParameters interface{}
type MSSqlExistingBackupSyncParameters interface{}
type FileProcessingResult interface{}
type DatabaseContainer interface{}
type ExportParameters interface{}
type PersistentObject interface{}
type AddLiveSourceParameters interface{}
type ASEDBConfig interface{}
type HostEnvironment interface{}
type ASESource interface{}
type LinkData interface{}
type OracleBaseLinkData interface{}
type Timeflow interface{}
type SshVerificationStrategy interface{}
type TypedObject interface{}
type OracleListener interface{}
type DatapointStream interface{}
type BaseGroupCapacityData interface{}
